---
title: "gen_rnd_samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Number of samples.
N <- 1000

# Vector to store the samples.
random_samples <- rep(NA, times = N)

# Mixture weights.
pi <- c(0.3, 0.5, 0.2)

# Mean of normals.
mu <- c(0, 10, 3)

# Std devs of normals.
s <- c(1, 1, 0.1)

# Determine threshold.
threshold <- cumsum(pi)

# Prepare plotting parameters.
range <- seq(-10, 20, by = 0.01)
```

```{r method1, echo=FALSE}

# Method 1

# Draw random samples.
for (i in 1:N) {
  u <- runif(1, min = 0, max = 1)

  if (u <= threshold[1]) {
    random_samples[i] = rnorm(1, mean = mu[1], sd = s[1])
  } else if (u <= threshold[2]) {
    random_samples[i] = rnorm(1, mean = mu[2], sd = s[2])
  } else {
    random_samples[i] = rnorm(1, mean = mu[3], sd = s[3])
  }
}


hist(random_samples, breaks = 25, probability = TRUE,
     main = "Random samples from a mixture of normal distributions")

lines(range, pi[1] * dnorm(range, mean = mu[1], sd = s[1]) +
             pi[2] * dnorm(range, mean = mu[2], sd = s[2]) +
             pi[3] * dnorm(range, mean = mu[3], sd = s[3]),
      col = "red", lwd = 2)   # lwd is line width.
```

```{r method2, echo=FALSE}

# Method 2 (sample K from a discrete distribution rather than i).

k <- sample(1:3, N, prob = pi, replace = TRUE)
random_samples <= rnorm(N, mean = mu[k], sd = s[k])


hist(random_samples, breaks = 25, probability = TRUE,
     main = "Random samples from a mixture of normal distributions")

lines(range, pi[1] * dnorm(range, mean = mu[1], sd = s[1]) +
             pi[2] * dnorm(range, mean = mu[2], sd = s[2]) +
             pi[3] * dnorm(range, mean = mu[3], sd = s[3]),
      col = "red", lwd = 2)   # lwd is line width.
```
